// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzPKR_xBUdh1rLpaNNjrf2LDHsO2jW3vA',
    appId: '1:574707704618:android:7b33496ad27601fee1f453',
    messagingSenderId: '574707704618',
    projectId: 'calendar-20251120-b4f0e',
    storageBucket: 'calendar-20251120-b4f0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHbn2K_vnR1fBu_tw0ir5u3FRRI2RTSQ0',
    appId: '1:574707704618:ios:12bddc83f61f91cde1f453',
    messagingSenderId: '574707704618',
    projectId: 'calendar-20251120-b4f0e',
    storageBucket: 'calendar-20251120-b4f0e.firebasestorage.app',
    iosClientId: '574707704618-bf2ov2dgf5uegomutk7vs4ujld41cc1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.ch22SchedulerSocial',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA34apE49kacOAZt4TCUMq3j4QA1tyd8kA',
    appId: '1:574707704618:web:528479846fefd9f4e1f453',
    messagingSenderId: '574707704618',
    projectId: 'calendar-20251120-b4f0e',
    authDomain: 'calendar-20251120-b4f0e.firebaseapp.com',
    storageBucket: 'calendar-20251120-b4f0e.firebasestorage.app',
    measurementId: 'G-XZ38NJ10RC',
  );

}